apiVersion: v1
kind: Service
metadata:
  name: llama4-scout-decode
  namespace: llm-d
  labels:
    app.kubernetes.io/name: llama4-scout-decode
    llm-d.ai/inferenceServing: "true"
    llm-d.ai/model: llama4-scout-modelservice
    llm-d.ai/role: decode
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: vllm
  - port: 5557
    targetPort: 5557
    protocol: TCP
    name: nixl
  selector:
    llm-d.ai/inferenceServing: "true"
    llm-d.ai/model: llama4-scout-modelservice
    llm-d.ai/role: decode
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: llama4-scout-service-account
  namespace: llm-d
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: llama4-scout-model-access
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["inference.networking.x-k8s.io"]
  resources: ["*"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: llama4-scout-model-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: llama4-scout-model-access
subjects:
- kind: ServiceAccount
  name: llama4-scout-service-account
  namespace: llm-d